libvpx: Roll latest libvpx
Pulling changes related to fixing a rare bitstream issue on video upscaling.

Upstream Hash: 8e9c9f118cda45013f14cce7961dcc8df78ffebf

Change-Id: I8639e6ef48f0309efaf6bdf745719beb71f7a58d

diff --git a/libvpx/configure b/libvpx/configure
--- a/libvpx/configure
+++ b/libvpx/configure
@@ -51,6 +51,7 @@ Advanced options:
   ${toggle_postproc_visualizer}   macro block / block level visualizers
   ${toggle_multi_res_encoding}    enable multiple-resolution encoding
   ${toggle_temporal_denoising}    enable temporal denoising and disable the spatial denoiser
+  ${toggle_webm_io}               enable input from and output to WebM container
 
 Codecs:
   Codecs can be selectively enabled or disabled individually, or by family:
@@ -160,11 +161,9 @@ for t in ${all_targets}; do
     [ -f ${source_path}/${t}.mk ] && enable_feature ${t}
 done
 
-for util in make perl; do
-    if ! ${util} --version >/dev/null; then
-        die "${util} is required to build."
-    fi
-done
+if ! perl --version >/dev/null; then
+    die "Perl is required to build"
+fi
 
 
 if [ "`cd ${source_path} && pwd`" != "`pwd`" ]; then
@@ -266,7 +265,6 @@ HAVE_LIST="
 "
 EXPERIMENT_LIST="
     multiple_arf
-    non420
     alpha
 "
 CONFIG_LIST="
@@ -314,6 +312,7 @@ CONFIG_LIST="
     postproc_visualizer
     os_support
     unit_tests
+    webm_io
     decode_perf_tests
     multi_res_encoding
     temporal_denoising
@@ -367,6 +366,7 @@ CMDLINE_SELECT="
     small
     postproc_visualizer
     unit_tests
+    webm_io
     decode_perf_tests
     multi_res_encoding
     temporal_denoising
@@ -689,6 +689,7 @@ process_toolchain() {
              10|11|12)
                  VCPROJ_SFX=vcxproj
                  gen_vcproj_cmd=${source_path}/build/make/gen_msvs_vcxproj.sh
+                 enabled werror && gen_vcproj_cmd="${gen_vcproj_cmd} --enable-werror"
                  ;;
              esac
              all_targets="${all_targets} solution"
@@ -702,6 +703,9 @@ process_toolchain() {
     if enabled postproc_visualizer; then
         enabled postproc || die "postproc_visualizer requires postproc to be enabled"
     fi
+
+    # Enable WebM IO by default.
+    soft_enable webm_io
 
     # Enable unit tests by default if we have a working C++ compiler.
     case "$toolchain" in
